apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: edenriel/hospital-notification
    newTag: 2325c83408a7ff1ee66621660f8723c2ca9c6bcb
