apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: edenriel/hospital-user
    newTag: 0995f110202f3fc3cb8a2086a406809ddf7ebc37
