apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: edenriel/hospital-user
    newTag: 556f4ca7f926fb0edb41c9d54b1f369b33761ad6
