apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base

images:
  - name: edenriel/hospital-user
    newTag: 605855f3ad0aa4a76bf4f3da39a0a880657bbf0d
