apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: edenriel/hospital-booking
    newTag: 69867a4b74884b0ed0bcbdb58b602a611410d6c8
