apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base

images:
  - name: edenriel/hospital-booking
    newTag: 2fa63b7614c857a4484820e5cf07511d7cf139ff
