apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base

images:
  - name: edenriel/hospital-booking
    newTag: c2ff8dbc10b11d9da0ae33df74eeec0d7a86abf6
