apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base

images:
  - name: edenriel/hospital-payment
    newTag: ea3ebe27bbab8e45c57ea8196f805d7d7c4f8ea7
