apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: edenriel/hospital-payment
    newTag: 07dbfab57e4ccc20552b8bda380d9774fa82b1d2
